# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Universal Robots .NET Communication SDK - UnderAutomation

banner: /assets/underautomation.png

cover: /assets/underautomation-universal-robots.png

description: UnderAutomation Universal Robots .NET Communication SDK (Software Development Kit) provides the ability to create customized .NET Core, .NET Framework and .NET Standard applications that can communicate with every UR robots. Ready to use examples for Windows, Mac OS and Linux, LabView, Node.js and Python are provided. It uses the TCP/IP Dashboard server to remote control the robot and the Client Interface to receive and decode data stream.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://underautomation.com" # the base hostname & protocol for your site, e.g.

github_username:  UnderAutomation

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - run.bat
   - run.command
   - install.bat
   - README.md
   - LICENSE.txt
   - CNAME
